name: 分布式缓存系统 CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      
    - name: 安装依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential g++ make jq curl lsof
        
    - name: 设置Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: 构建Docker镜像
      run: |
        docker-compose build
        
    - name: 启动服务
      run: |
        docker-compose up -d
        sleep 30
        
    - name: 健康检查
      run: |
        for port in 9527 9528 9529; do
          curl -f http://localhost:$port/health
        done
        
    - name: 运行基础测试
      run: |
        # 简单测试，避免CI超时
        curl -X POST -H "Content-Type: application/json" \
             -d '{"test":"ci-test"}' http://localhost:9527/
        curl http://localhost:9527/test | grep "ci-test"
        curl -X DELETE http://localhost:9527/test
        
    - name: 查看服务日志
      if: failure()
      run: |
        docker-compose logs
        
    - name: 清理
      if: always()
      run: |
        docker-compose down
